let musicList = [
    {
        id: 1,
        name: "Once Upon A Time Remix",
        artist: "Original Mix",
        src: "once-upon-a-time-remix",
        lyric: [
            'Once upon a time',
            'A girl, with moonlight in her eyes',
            'Put her hand in mine',
            'And said she loved me so',
            'But that was once upon a time',
            'Very long ago',

            'Once upon a hill',
            'We sat beneath a willow tree',
            'Counting all the stars, and waiting for the dawn',
            'But that was once upon a time',
            'Now the tree is gone',

            'How the breeze ruffled through her hair',
            "How we always laughed, as though tomorrow wasn't there",
            "We were young, and didn't have a care",
            'Where did it go?',

            'Once upon a time',
            'The world was sweeter than we knew',
            'Everything was ours',
            'How happy we were then',
            'But somehow, once upon a time',
            'Never comes again',

            'Once upon a time',
            'Never comes again'
        ],
    },
    {
        id: 2,
        name: "Một Bước Yêu Vạn Dặm Đau",
        artist: "Mr.Siro",
        src: "mot-buoc-yeu-van-dam-dau-mr-siro",
        lyric: [
            'Một thế giới hư ảo, nhưng thật ấm áp',
            'Em xuất hiện khiến những băng giá đời anh bỗng dần tan đi',
            'Cuộc đời anh đặt tên là muộn phiền nên làm sao dám mơ mình may mắn',
            'Được trọn vẹn cùng em',
            'Ta phải xa em mặc kệ nước mắt em rơi',
            'Vì những nguyên do cả đời không dám đối diện',
            'Chỉ còn vài gang tấc nhưng lại xa xôi',
            'Tình mình tựa đôi đũa lệch, đành buông trôi',
            'Cầu mong em sẽ sớm quên được tất cả',
            'Tìm thấy một người, xứng đáng ở bên',
            'Từ nay duyên kiếp bỏ lại phía sau',
            'Ngày và bóng tối chẳng còn khác nhau',
            'Chẳng có nơi nào yên bình được như em bên anh',
            'Hạt mưa bỗng hoá thành màu nỗi đau',
            'Trời như muốn khóc ngày mình mất nhau',
            'Có bao nhiêu đôi ngôn tình',
            'Cớ sao lìa xa mình ta?',
            'Là nhân duyên trời ban',
            'Cớ sao mình chẳng thể thành đôi?',
            'Tại sao quá ngu ngốc',
            'Bỏ lại mảnh ghép mà đối với nhau là tất cả',
            'Còn mình thì vụn vỡ',
            'Thế giới thực tại ồn ào vẫn thấy cô đơn',
            'Còn hai ta thì khác, chỉ nhìn thôi tim đã thấu',
            'Từ nay duyên kiếp bỏ lại phía sau',
            'Ngày và bóng tối chẳng còn khác nhau',
            'Chẳng có nơi nào yên bình được như em bên anh',
            'Hạt mưa bỗng hóa thành màu nỗi đau',
            'Trời như muốn khóc ngày mình mất nhau',
            'Có bao nhiêu đôi ngôn tình',
            'Cớ sao lìa xa mình ta?',
            'Từ nay danh giới của hai chúng ta',
            'Là yêu nhưng không thể nào bước qua',
            'Ngọn cỏ ven đường thôi mà',
            'Làm sao với được mây?',
            'Từ sau câu giã từ êm ái kia',
            'Chẳng cơn bão lớn nào bằng bão lòng',
            'Gặp trong mơ mà cũng không dám gào lên',
            'Anh thương em',
        ],
    },
    {
        id: 3,
        name: "Bên Ấy Bên Này",
        artist: "Long Cao",
        src: "ben-ay-ben-nay",
        lyric: [
            'Và giờ như thế hôm qua người về bên ấy',
            'Để lại anh đấy hôm nay lặng thầm bên này',
            'Đường mòn nào thân quen đã như đổi thay',
            'Tìm niềm vui mới hôm nay cùng người bên ấy',
            'Liệu em có nhớ hôm qua ngọt ngào bên này',
            'Và ngày nào đôi tay xiết trong vòng tay',
            'Kỉ niệm đầy vơi phía sau dịu dàng tựa như lúc đầu',
            'Chỉ là ta không còn gần nhau',
            'Và nếu có phép màu biết đi tìm nơi đâu',

            'ĐK:',
            'Để bây giờ ngày đầy nỗi nhớ đêm giật mình ngu ngơ',
            'Giờ này mình hai nơi Bên ấy bên này',
            'Mà lòng còn cứ ngỡ hay chỉ là trong mơ',
            'Giờ này mình xa xôi ai đắp ai bồi',
            'Tìm gì ở quá khứ Nay chẳng còn thế nữa',
            'Chỉ là những giấc mơ xa tầm tay',
            'Dặn lòng đừng tiếc nuối cho mình đành buông lơi',
            'như vậy thôi…Bên ấy bên này',
            'Cho bao nhiêu yêu thương muộn màng',
            'Dần ngủ yên đi về nơi quên lãng',
            'Cho đôi ta thôi mong đợi chờ',
            'Về một ngày mai mà chẳng đến bao giờ',
            'Tìm lại bình yên sâu trong tim như bấy lâu',
            'tìm lại hồn nhiên như khi ta chưa bắt đầu',
            'Biết đến khi nào…'
        ],
    },
    {
        id: 4,
        name: "That Girl",
        artist: "Olly Murs",
        src: "that-girl",
        lyric: [
            'There’s a girl but I let her get away',
            'It’s all my fault cause pride got in the way',
            'And I’d be lying if I said I was ok',
            'About that girl the one I let get away',

            'I keep saying no',
            'This can’t be the way we’re supposed to be',
            'I keep saying no',
            'There’s gotta be a way to get you close to me',
            'Now I know you gotta',

            'Speak up if you want somebody',
            'Can’t let him get away, oh no',
            'You don’t wanna end up sorry',
            'The way that I’m feeling everyday',
            'No no no no',
            'There’s no hope for the broken heart',
            'No no no no',
            'There’s no hope for the broken',

            'There’s a girl but I let her get away',
            'Its my fault cause I said I needed space',
            'I’ve been torturing myself night and day',
            'About that girl, the one I let get away',
            'I keep saying no',
            'This ain’t the way it’s supposed to be',
            'I keep saying no',
            'There’s gotta be a way',
            'There’s gotta be a way',
            'To get you close to me',
            'You gotta',

            'Speak up if you want somebody',
            'Can’t let him get away, oh no',
            'You don’t wanna end up sorry',
            'The way that I’m feeling everyday',
            'No no no no',
            'There’s no hope for the broken heart',
            'No no no no',
            'There’s no hope for the broken',

            'No home for me',
            'No home cause I’m broken',
            'No room to breathe',
            'And I got no one to blame',
            'No home for me',
            'No home cause I’m broken',
            'About that girl',
            'The one I let get away',

            'So you better',
            'Speak up if you want somebody',
            'Can’t let him get away no no',
            'You don’t wanna end up sorry',
            'The way that I’m feeling everyday',
            'Don’t you know',
            'No no no no',
            'There’s no hope for the broken heart',
            'Don’t you know',
            'No no no no',
            'There’s no hope for the broken',
            'You don’t wanna lose at love',
            'It’s only gonna hurt too much',
            'I’m telling you',
            'You don’t wanna lose at love',
            'It’s only gonna hurt too much',
            'You don’t wanna lose at love',
            'Cause There’s no hope for the broken heart',
            'There’s that girl',
            'The one I let get away'
        ],
    },
    {
        id: 5,
        name: "3107",
        artist: "W/n ft. ( Nâu , Duongg )",
        src: "duongg-3107",
        lyric: [
            'Có cơn mưa nào đôi mình đi qua',
            'Anh đến bên em ngày đôi mình chia xa',
            'Mùa lá rơi bên hồ',
            'Nỗi cô đơn lớn lên',
            'Mùa thu ấy em không còn bên cạnh anh nữa',
            'Anh vẫn đứng nơi đây chờ em cùng cơn mưa',
            'Chúng ta sau này',
            'Chẳng có chúng ta bây giờ',
            'Một người âm thầm đứng dưới mưa nhìn em',
            'Một người giữa thành phố vẫn cứ chờ em',
            'Vì sao cứ nơi đó mà',
            'Ánh dương giơ nơi đâu?',
            'Giờ này chỉ nỗi nhớ cứ mãi nhiều thêm',
            'Giờ này chỉ mình ta với những tháng năm dài',
            'Có khi em chẳng còn yêu anh',
            'Như trái tim ta từng chung lối đi',
            '',
            'Rap:',
            '',
            'Anh đi một vòng thị trấn',
            'Trên con đường cũ ta đi',
            'Vòng bánh xe như thế cứ chạy',
            'Hai tuyến đường ngược chiều ta nghĩ',
            'Chắc em cũng quên tên đường này rồi',
            'Nhánh hoa sữa nhẹ bay đi khắp lối',
            'Em cũng giống như anh của ngày trước',
            'Hai con đường về nhà khi sắp tối',
            'Anh còn nhớ hồi đó ta đi học',
            'Lúc tan trường thì em ngồi sau xe',
            'Lúc em buồn thì anh hay trêu chọc',
            'Bảo em cười thì chuyện cho nhau nghe',
            'Rồi vào quán mua món mà em thích',
            'Em mỉm cười làm anh cũng vui lây',
            'Nhưng hồi đó thì vẫn là hồi đó',
            'Anh cảm ơn em đã để lại chuỗi ngày',
            'Một người âm thầm đứng dưới mưa nhìn em',
            'Một người giữa thành phố vẫn cứ chờ em',
            'Vì sao cứ nơi đó mà',
            'Ánh dương giơ nơi đâu?',
            'Giờ này chỉ nỗi nhớ cứ mãi nhiều thêm',
            'Giờ này chỉ mình ta với những tháng năm dài',
            'Có khi em chẳng còn yêu anh',
            'Như trái tim ta từng chung lối đi',
            '',
            'Có cơn mưa nào đôi mình đi qua',
            'Anh viết cho em bài ca mùa yêu xa',
            'Mùa lá rơi bên hồ nỗi cô đơn lớn lên',
            'Mùa thu ấy',
            'Anh không còn bên cạnh em nữa',
            'Em vẫn đứng nơi đây chờ anh cùng cơn mưa',
            'Chúng ta sau này chẳng có chúng ta bây giờ',
            'Đêm dần buông',
            'Chỉ có đôi ta đứng đây hơi buồn',
            'Nhấm nháp những suy tư',
            'Của ngày hôm qua vừa đây, đã xa',
            'Riêng mình ta',
            'Vẫn mãi lang thang dưới ánh chiều tà',
            'Vẫn nỗi nhớ miên man',
            'Ký ức bên em bây giờ đang ở một nơi xa',
            'Chỉ cần bên nhau như những ngày ấy',
            'Anh sẽ cùng em đi hết tháng ngày',
            'Để trong cơn mơ anh chẳng tìm thấy',
            'Để anh bơ vơ mãi phút nơi đây',
            'Tình yêu khi xưa đôi ta vụn vỡ',
            'Trong một chiều mưa hai đứa chia tay',
            'Chỉ cần cho anh được thêm một chút',
            'Cho anh được gần bên em',
            '',
            'Xin lỗi vì những cuộc điện thoại',
            'Đã làm phiền em với nửa kia',
            'Dưới góc phố lặng thinh',
            'Tiếng bước chân chậm chạp',
            'Lúc giữa khuya',
            'Tất nhiên thì anh cũng như họ',
            'Chọn buông bỏ để em thấy yên bình',
            'Còn riêng phần anh',
            'Thì lại thầm trách mọi thứ',
            'Trái ngược với duyên tình, em!',
            '',
            'Lúc mình buồn nhìn trời và thở hắc',
            'Mưa tháng bảy là cơn buồn dào dạt',
            'Lẫn về tình yêu mà anh đã lỡ mất',
            'Hẳn ai cũng từng nếm phải',
            'Cảm giác trống trải',
            'Trong lòng mình em ha',
            'Như em cũng từng đau khổ vì họ rồi',
            'Lại thức trắng bao đêm qua',
            'Nếu ta có dịp ngồi lại',
            'Thì anh xin phép kể cho em nghe',
            'Bình yên của anh thì cũng giống như họ',
            'Là có em ngồi phía sau xe',
            'Là buộc phải cố lượm lặt được hết',
            'Những thứ trước kia đã xa mình',
            'Là em hồi đó hay là anh bây giờ',
            'Cô đơn đứng giữa ngã ba tình',
            'Hoàng hôn tháng bảy chưa bao giờ',
            'Giết chết trái tim buồn bã đã cũ mềm',
            'Bầu trời đêm nay lại có mưa rơi',
            'Qua một ô cửa đã phủ rèm, em',
            'Anh còn chẳng dám khẳng định',
            'Mình đã nhớ về em bao nhiêu đêm',
            'Nhưng sau tất cả thì chỉ có',
            'Anh và anh tự buộc mình yêu em',
            '',
            'Chỉ cần bên nhau như những ngày ấy',
            'Anh sẽ cùng em đi hết tháng ngày',
            'Dù chờ ngàn năm anh vẫn ở đấy',
            'Dù anh đã cố gắng nghĩ đến em',
            'Rồi trong nhân gian bao nhiêu người đến',
            'Thanh xuân này anh chỉ muốn bên em',
            'Dìu nhau đi qua những con phố dài',
            'Chỉ yêu đôi ta chẳng biết đúng sai',
            'Vì sao?',
            '',
            'Đêm chờ đông',
            'Gió vẫn lao xao khiến ta thêm sầu',
            'Giấu ký ức nơi đây vào gọn trong tim',
            'Dù mai đổi thay',
            'Riêng mình ta',
            'Vẫn mãi cô đơn dưới ánh trăng vàng',
            'Vẫn nỗi nhớ khi xưa',
            'Những lúc bên em',
            'Bây giờ đang ở một nơi xa',
        ],
    },
    {
        id: 6,
        name: "3107-2",
        artist: "DuongG x NÂU x W/N",
        src: "duongg-3107-2",
        lyric: [
            'Đến bao giờ mới có thể quên đi những câu chuyện mà ta đã trao',
            'Đến bao giờ mới có thể yêu một người đến sau',
            'Đến bao giờ mới có thể quên đi những kỉ niệm mà ta đã qua',
            'Và nếu hôm nay là ngày mà chúng ta đã rời xa',
            'Chỉ cần ai đó cạnh bên dừng lại và níu lấy em chỉ một phút giây',
            'Dù là có đúng hay sai vẫn cứ yêu thêm một lần chẳng cần nghi ngại',
            'Ngày dài vẫn thế cứ thế trôi hoài lạc mất nhau sao mình còn đi mãi',
            'Nơi anh đến sẽ là một nơi chẳng còn có em.',
            '',
            'Rap:',
            '',
            'Anh có bàn tay này nắm tất cả nhưng không thể nắm được tay em',
            'Anh có niềm tin là thứ duy nhất ở lại cuối cùng.',
            'Anh đã từng có vầng trời của mình nhưng trời chỉ toàn đám mây đen',
            'Cũng chẳng quán quen đường mình thường ghé vào dịp cuối tuần.',
            '',
            'Anh thấy không ổn nhưng vẫn cố tỏ ra không sao',
            'Điều tệ nhất là em đi mất chỉ còn đôi tất cuối cùng trong bao',
            'Mưa cũng chẳng giúp anh được gì ngoài việc làm ướt đi áo sơ mi',
            'Thắt cà vạt chỉnh chu lại áo nhưng cuối cùng vẫn bị em lơ đi.',
            '',
            'Biết bao giờ mới có thể quên đi những câu chuyện mà ta đã trao',
            'Đến bao giờ mới có thể yêu một người đến sau',
            'Đến bao giờ mới có thể quên đi những kỉ niệm mà ta đã qua',
            'Và nếu hôm nay là ngày mà chúng ta đã rời xa.',
            'Chỉ cần ai đó cạnh bên dừng lại và níu lấy em chỉ một phút giây',
            'Dù là có đúng hay sai vẫn cứ yêu thêm một lần chẳng cần nghi ngại',
            'Ngày dài vẫn thế cứ thế trôi hoài lạc mất nhau sao mình còn đi mãi',
            'Nơi anh đến sẽ là một nơi chẳng còn có em.',
            'Giờ giọt nước mắt cứ thế lăn dài ngày tháng trôi đi chẳng thể níu ai',
            'Rồi ngày mai đến ra sao khi cứ trông mong một người sẽ còn ở lại',
            'Ngày hạ năm ấy còn nhớ những gì và chúng ta đã là hai thế giới',
            'Thế giới ấy bây giờ chẳng còn điều gì giống ai.',
        ],
    },
    {
        id: 7,
        name: "3107-3",
        artist: "DuongG x NÂU x W/N",
        src: "duongg-3107-3",
        lyric: [
            'Xin lỗi em về những chuyện mà ta đã nghĩ',
            'Xin lỗi em về những gì mà ta đã nói',
            'Vì bao câu chuyện mình lúc xưa',
            'Giờ đây chẳng thể viết tiếp được',
            'Chỉ là xa thôi mà, chẳng khi nào ta ngừng nghĩ đến nhau.',
            'Bao tháng năm vô tư hồn nhiên biết mấy',
            'Những chuyến xe ta đi cùng năm tháng ấy',
            'Giờ đây chỉ là những thước phim',
            'Phai mờ sâu vào những kỉ niệm',
            'Điều duy nhất bây giờ, còn nhớ chỉ là vài câu',
            'Xin lỗi vì những lời hứa, xin lỗi chẳng yêu được nữa',
            'Xin lỗi vì em chẳng thể đến cạnh anh mỗi khi trời đổ mưa',
            'Xin lỗi vì em đã đúng, xin lỗi vì anh đã sai',
            'Xin lỗi vì ta chẳng thể đi cùng nhau để bây giờ cách xa',
            'Vòng xe thứ nhất là đón đưa em qua từng điểm hẹn ngày đầu tiên',
            'Góc phố đèn mờ có ngọn đèn cũ thổi hồn nỗi buồn này vào tim',
            'Vòng xe thứ hai là cùng với em đón nắng ngày xuân vào chiều tà',
            'Là thèm được nhớ nhưng rồi phải buông với họ gọi đó là yêu xa',
            'Em đâu hay biết, vẫn có người đứng chờ đợi em tới giữa khuya',
            'Chỉ để quan tâm em dẫu biết rằng em đang bận lòng với nửa kia',
            'Cùng một góc nhìn nhưng cảm xúc bây giờ dần trở nên vô vị',
            'Đứng trên dốc tình chỉ là mỗi góc nhìn để thấy được em và đô thị',
            'Ở trong thành phố, Lòng đành cố gào thét khiến cổ họng khát khô',
            'Bây giờ là một giờ sáng, Cafe đậm hòa cùng gói Bastos',
            'Anh từng sống trong tim em, quá thời hạn nhưng rồi phải ra đi',
            'Thành phố hồi đó có trời gió và em còn hơn cả Paris',
            '"Anh cũng chỉ nghĩ về những thứ mơ mộng thôi',
            'Dẫu biết thực tế khác xa vời vợi rồi',
            'Cũng chả rõ mình đã nhớ em về bao nhiêu đêm',
            'Nhưng mà ít nhiều gì thì anh cũng đã từng là một người rất yêu em',
        ],
    },
    {
        id: 8,
        name: "3107-4",
        artist: "Erik ft Nâu x W/N",
        src: "erik-3107-4",
        lyric: [
            'Bầu trời xanh ngát',
            'Mình anh đứng giữa cơn mơ',
            'Dưới những màn đêm chỉ có riêng anh mãi chờ',
            '',
            'Ngày em bước đến',
            'Làm con tim anh ấm lên',
            'Chỉ mong đôi ta chẳng phải cách xa',
            '',
            'Cứ như vậy mỗi ngày cứ hoài trôi đi',
            'Chính em là những người khiến anh đổi thay',
            'Chẳng có gì nuối tiếc, khi em ở bên cạnh anh',
            'Đến bây giờ kỷ niệm chỉ là hư vô',
            'Còn bàn tay khi xưa đã xa nơi đây',
            'Năm ấy đôi ta, đã có nhau mà',
            '',
            'RAP:',
            '',
            'Anh đang không biết điều gì khiến mình buồn và rồi cuốn vào vòng xoay',
            'Khi cô ta tắt màn hình chờ, mỗi lần hẹn hò chẳng còn cầm tay',
            'Anh đâu còn thời giờ thay vì đợi chờ hay là nhắc về người ấy',
            'Em đâu còn tin vào anh, vào em, vào tất cả những gì mình thấy',
            '',
            'Pick up your phone, em có nghe được giọng anh nói',
            'Giọng anh nói, qua điện thoại',
            'Anh vẫn đang có vài câu hỏi anh không dám nói qua điện thoại',
            'Tình ca buồn và cafe gói ! Không chánh án, không kiện tội',
            'Nếu em bận thì đừng nghe máy',
            '',
            'Anh cũng rất vui',
            'Oke, anh rất hài lòng khi được gặp em',
            'Anh bận bôn ba, vì sợ giông tố ngày mai sẽ còn ập đến',
            'Anh không quan tâm, chỉ nói đến chuyện sau này sẽ còn gặp nhau',
            'Nhưng mà cứ dưới nước thì biết bao giờ con thuyền của mình mới được cập bến',
            '',
            'Anh vẫn đang sống như em',
            'Không phải tồn tại cho đến khi em mập mờ quay đi',
            'Những ngày còn lại, anh không biết đã làm những gì khiến em nghi ngờ',
            'Nhưng mà không tin cứ nhìn xem',
            'Đến khi thành phố của mình tắt đèn',
            'Anh lại vội đi tìm em',
            '',
            'ERIK:',
            '',
            'Cứ như vậy mỗi ngày cứ hoài trôi đi',
            'Chính em là những người khiến anh đổi thay',
            'Chẳng có gì nuối tiếc, khi em ở bên cạnh anh',
            'Đến bây giờ kỷ niệm chỉ là hư vô',
            'Còn bàn tay khi xưa đã xa nơi đây',
            'Năm ấy đôi ta, đã có nhau mà',
            '',
            'Chỉ là nỗi nhớ … mà anh cất giữ bao lâu',
            'Những giấc ngủ say người ấy theo ai mất rồi',
            'Ngày em bước đến',
            'Làm con tim anh ấm lên',
            'Chỉ mong đôi ta chẳng phải cách xa',
        ],
    },
    {
        id: 9,
        name: "3107-7",
        artist: "W/N ft. titie, Duongg",
        src: "duongg-3107-7",
        lyric: [
            'Ta đang qua nơi đây anh vẫn tồn tại',
            'Yêu đơn phương đôi khi cứ ngỡ từng ngày',
            'Ngàn lời yêu khi ấy em nói anh cố giữ nó thật chắc nơi tim này',
            'Vài nụ hôn đêm đó ta đã vội trao vô cớ ở trong cơn mơ ấy',
            'Chẳng cần như gió với mây ngàn',
            'Chẳng cần như trăng với đêm tàn',
            'Chỉ cần em cạnh bên đêm nay một chút thôi',
            'Rồi đêm đến hãy đến bên anh một chút thôi',
            '',
            'I’m coming love',
            'Coming love',
            'I’m coming love',
            'I’m coming love',
            '',
            'Ta như ai đang nơi trao tình đầu',
            'Yêu đơn phương đôi khi cứ ngỡ thật lâu',
            'Vì ta đã có những vụn vỡ gửi đến rồi đi thật nhanh tôi một mình',
            'Đành chôn giấu ký ức cùng mây gửi đi bỏ lại mình tôi trong đêm tối',
            'Chẳng cần như gió với mây ngàn',
            'Chẳng cần như trăng với đêm tàn',
            'Chỉ cần em cạnh bên đêm nay một chút thôi',
            'Rồi đêm đến hãy đến bên anh một chút thôi',
            '',
            'I’m coming love',
            'Coming love',
            'I’m coming love',
            'I’m coming love',
        ],
    },
    {
        id: 10,
        name: "W/n - id 072019",
        artist: "3107 ft 267",
        src: "id-072019",
        lyric: [
            'Có cơn mưa nào đôi mình đi qua',
            'Anh đến bên em ngày đôi mình chia xa',
            'Mùa lá rơi bên hồ',
            'Nỗi cô đơn lớn lên',
            'Mùa thu ấy em không còn bên cạnh anh nữa',
            'Anh vẫn đứng nơi đây chờ em cùng cơn mưa',
            'Chúng ta sau này',
            'Chẳng có chúng ta bây giờ',
            'Một người âm thầm đứng dưới mưa nhìn em',
            'Một người giữa thành phố vẫn cứ chờ em',
            'Vì sao cứ nơi đó mà',
            'Ánh dương giơ nơi đâu?',
            'Giờ này chỉ nỗi nhớ cứ mãi nhiều thêm',
            'Giờ này chỉ mình ta với những tháng năm dài',
            'Có khi em chẳng còn yêu anh',
            'Như trái tim ta từng chung lối đi',
            '',
            'Rap:',
            '',
            'Anh đi một vòng thị trấn',
            'Trên con đường cũ ta đi',
            'Vòng bánh xe như thế cứ chạy',
            'Hai tuyến đường ngược chiều ta nghĩ',
            'Chắc em cũng quên tên đường này rồi',
            'Nhánh hoa sữa nhẹ bay đi khắp lối',
            'Em cũng giống như anh của ngày trước',
            'Hai con đường về nhà khi sắp tối',
            'Anh còn nhớ hồi đó ta đi học',
            'Lúc tan trường thì em ngồi sau xe',
            'Lúc em buồn thì anh hay trêu chọc',
            'Bảo em cười thì chuyện cho nhau nghe',
            'Rồi vào quán mua món mà em thích',
            'Em mỉm cười làm anh cũng vui lây',
            'Nhưng hồi đó thì vẫn là hồi đó',
            'Anh cảm ơn em đã để lại chuỗi ngày',
            'Một người âm thầm đứng dưới mưa nhìn em',
            'Một người giữa thành phố vẫn cứ chờ em',
            'Vì sao cứ nơi đó mà',
            'Ánh dương giơ nơi đâu?',
            'Giờ này chỉ nỗi nhớ cứ mãi nhiều thêm',
            'Giờ này chỉ mình ta với những tháng năm dài',
            'Có khi em chẳng còn yêu anh',
            'Như trái tim ta từng chung lối đi',
            '',
            'Có cơn mưa nào đôi mình đi qua',
            'Anh viết cho em bài ca mùa yêu xa',
            'Mùa lá rơi bên hồ nỗi cô đơn lớn lên',
            'Mùa thu ấy',
            'Anh không còn bên cạnh em nữa',
            'Em vẫn đứng nơi đây chờ anh cùng cơn mưa',
            'Chúng ta sau này chẳng có chúng ta bây giờ',
        ],
    },
    {
        id: 11,
        name: "W/n - a b c d x y z n m a s a d",
        artist: "3107",
        src: "song-24",
        lyric: [
            'Chỉ là vì nơi này chỉ còn bóng tối cô đơn mình anh',
            'Muốn rời đi khỏi đây chỉ vì anh quá yếu đuối',
            'Khóc nữa đi, em ơi',
            'Hãy để nước mắt rơi trên làn mi',
            'Chỉ vì một thứ nơi đây mà thứ nơi đây',
            'Là vì anh quá yếu đuối',
            'Chỉ tìm trong giấc mơ',
            'Một mình anh ngây thơ',
            'Chỉ là người đứng chờ',
            'Chạy đi đâu em hỡi',
            'Chạy vào trong giấc mơ',
            'Một mình anh tìm lối',
            'Chẳng thể nào thoát ra...',
            '',
            'Đêm anh lại nhớ đến em, nhớ lại về chuyện cũ',
            'Nhớ lại hình bóng qua nỗi thân quen bên trong tâm hồn vẫn hiện hữu',
            'Anh nhớ lời nói của cô gái đó, không phải qua chiếc điện thoại',
            'Anh nhớ Quảng Nam vào ngày trái gió',
            'Ta không yêu theo kiểu hiện đại',
            '',
            'Em có còn nhớ ngày ta xa chính xác vào ngày đông chí',
            'Anh đã lặng lẽ mua 5 đóa hồng dù không có tiền ở trong ví',
            'Anh nghĩ đó là món quà kỷ niệm tặng em trước lúc em bước đi',
            'Rồi giam mình vào trong căn phòng nhỏ nhìn bức ảnh đó đến ướt mi',
            '',
            'Anh biết tình anh như ly cà phê, thấm dần vào những suy nghĩ',
            'Khi ta không phải là cặp tình nhân nhưng có thể trở thành tri kỷ',
            'Anh không như họ, anh vẫn muốn đi tìm lại anh của ngày đó',
            'Một ngày bình thường nhìn nỗi nhớ chạy dọc trên ban công đầy gió',
            '',
            'Tất cả phê sữa hòa quyện lại với vị khói thuốc Sài Gòn bạc',
            'Là cách anh rap, cách thả hồn vào những ngày dài còn nhạc',
            'Là cứ như thế, những giai điệu xuất hiện vào 2 giờ đêm',
            'Nói cho em biết trước hiên nhà vẫn có một ai chờ em',
            '',
            'Là vì anh quá yếu đuối',
            'Chỉ tìm trong giấc mơ',
            'Một mình anh ngây thơ',
            'Chỉ là người đứng chờ',
            'Chạy đi đâu em hỡi',
            'Chạy vào trong giấc mơ',
            'Một mình anh tìm lối',
            'Chẳng thể nào thoát ra...',
        ],
    },
    {
        id: 12,
        name: "Crush 2",
        artist: "W/n ft.Tez, Tien",
        src: "crush-2",
        lyric: [
            'Một mình em ở đây',
            'Lặng thầm mãi lướt face',
            'Đợi chờ anh đấy nhưng',
            'Chẳng thấy xuất hiện',
            'uhhh',
            'Mặc kệ biết đúng sai',
            'Mình ngồi đến sớm mai',
            'Nhìn lại đôi khi mặt trời',
            'Vừa mới lên',
            'Mùa hạ dần ghé chơi',
            'Chợt nhìn anh chút thôi',
            'Mà nào ngờ đâu tim này say mất rồi',
            'Lại là đôi mắt anh',
            'Lạc vào tâm trí em',
            'Chẳng hiểu vì sao cứ nghĩ',
            'Đến mãi thôi',
            'Lỡ say anh mất rồi',
            'Love',
            'Love',
            'Love',
            'Vì lỡ say anh mất rồi',
            'Love',
            'Love',
            'Love',
            'Lỡ say anh mất rồi',
            'Love',
            'Love',
            'Love',
            'Giờ chẳng cần nên suy nghĩ',
            'Chẳng cần nên suy nghĩ',
            'Lỡ yêu anh mất rồi',
            'Love',
            'Love',
            'Love',
            'Lỡ yêu anh mất rồi',
            'Love',
            'Love',
            'Love',
            'Lỡ yêu anh mất rồi',
            'Love',
            'Love',
            'Love',
            'Giờ chẳng cần nên suy nghĩ',
            'Chẳng cần nên suy nghĩ',
        ],
    },
    {
    id: 13,
    name: "Emm đã từ bỏ rồi đấy",
    artist: "cover",
    src: "em-da-tu-bo-roi-day",
    lyric: []
},
];
